### ISSUE TITLE
The code is what seems to be wrong

### ISSUE THREAD

**Issue by eanson023** [zhexu1997/HiSA#2]
Hi author:
       Thank you for your wonderful contribution to Temporal Sentence Grounding in Videos, I read your code and found that there is a missing place. 
       
in [localization_HiSA.py](https://github.com/zhexu1997/HiSA/blob/main/modeling/localization_HiSA.py)  line 153-159
```python
            for i in range(b):
                cos_similarity = nn.CosineSimilarity(dim=1)(text_global[i].expand(text_global.size()), video_global)
                cos_similarity = torch.exp(cos_similarity)
                vcon_loss += (-1) * torch.log(cos_similarity[i] / cos_similarity.sum())
            for i in range(b):
                cos_similarity = nn.CosineSimilarity(dim=1)(video_global[i].expand(video_global.size()), text_global)
                cos_similarity = torch.exp(cos_similarity)
                tcon_loss += (-1) * torch.log(cos_similarity[i] / cos_similarity.sum())

        con_loss = (vcon_loss + tcon_loss) / b
        return con_loss
```

Did you forget to divide by `tao` here?

**Comment by zhexu1997** [comment]
Thanks for being interested in our work.  As shown in our paper, we set the temperature parameter tau to 1 in our experiment. The performance may increase when tau changes.

**Comment by eanson023** [comment]
OK, I got it
